channel: phi_alpha
name: qd_fold
mode: kp_and_ll
coupling: independent
channels:
  - spin: spin1
    potential:
      type: folded
      fold: true
      phiN_central:
        mode: quartet_plus_doublet
        doublet_b_fm: 0.55
        doublet_target_f0: -1.54
      density:
        type: gaussian_sg
        A: 4
        rms_fm: 1.56
