channel: phi_alpha
name: q_chizzali_tpe_fold
mode: kp_and_ll
coupling: independent
channels:
  - spin: spin1
    potential:
      type: folded_phi_n
      quartet: chizzali_ta12_tpe
      fold: true
      density:
        type: gaussian_sg
        A: 4
        rms_fm: 1.56
